In [1]:
import h5py as h5
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

In [2]:
#Snapshot 0
filein_000=h5.File("simulation.hdf5/snap_000.hdf5.html",'r')


header_000 = filein_000['Header']
stars_000 = filein_000['PartType2']
gas_000 = filein_000['PartType0']
BH_000 = filein_000['PartType5']
#nstars = filein['']
BH_positions_000 = np.asarray(BH_000['Coordinates'])
g_positions_000 = np.asarray(gas_000['Coordinates'])
s_positions_000 = np.asarray(stars_000['Coordinates'])
g_mass_000 = np.asarray(gas_000['Mass'])
s_mass_000 = np.ones(500000)*(header_000.attrs.__getitem__('MassTable')[2])
BH_mass_000 = np.asarray(BH_000['BH_Mass'])

In [3]:
# fig = plt.figure(figsize=(14,14))
# gs = gridspec.GridSpec(2, 2)

In [4]:
# given the position and masses of the particles, finds their center of mass
def findCenterMass(r,m):
    com=np.zeros(3)
    for i in range(3):
        com[i]=np.sum(r[:,i]*m[:])/np.sum(m[:])
    return com

In [5]:
gasCom_000 = findCenterMass(g_positions_000,g_mass_000)
starCom_000 = findCenterMass(s_positions_000,s_mass_000)
nCom_000 = np.zeros(3)
gasCom_000, starCom_000, nCom_000

(array([ 0.01116187,  0.00303726, -0.00418845]),
 array([  1.16131842e-03,   1.04191301e-03,   7.89113621e-05]),
 array([ 0.,  0.,  0.]))

In [482]:
# comdata=open("centerofmass.txt","w")
# Gas = 'Gas'
# Stars = 'Stars'
# NewStars = 'New Stars'
# # np.savetxt(comdata, (gasCom,starCom,nCom), , comments='')
# # np.savetxt(comdata,([gasCom,starCom]), delimiter='\t', header='gas,stars,new stars')
# c= np.zeros(3)
# a=(gasCom,starCom,c)

# for val in (a):
#     comdata.write('{}'.format(val))
# comdata.close()


Gcom_000 = findCenterMass(s_positions_000,s_mass_000)
Gcom_401 = findCenterMass(np.concatenate((s_positions_401,n_positions_401),axis=0),np.concatenate((s_mass_401,n_mass_401),axis=0))

In [485]:
np.concatenate((s_positions_401,n_positions_401),axis=0).shape
# gin = np.loadtxt('centerofmass.txt', delimiter=',')

(615694, 3)

In [8]:
#Snapshot 401
filein_401 = h5.File("simulation.hdf5/snap_401.hdf5.html",'r')

header_401 = filein_401['Header']
stars_401 = filein_401['PartType2']
gas_401 = filein_401['PartType0']
BH_401 = filein_401['PartType5']
nstars_401 = filein_401['PartType4']
BH_positions_401 = np.asarray(BH_401['Coordinates'])
g_positions_401 = np.asarray(gas_401['Coordinates'])
s_positions_401 = np.asarray(stars_401['Coordinates'])
n_positions_401 = np.asarray(nstars_401['Coordinates'])
n_mass_401 = np.asarray(nstars_401['Mass'])
g_mass_401 = np.asarray(gas_401['Mass'])
s_mass_401 = np.ones(500000)*(header_401.attrs.__getitem__('MassTable')[2])
BH_mass_401 = np.asarray(BH_401['BH_Mass'])

In [9]:
nCom_401 = findCenterMass(n_positions_401,n_mass_401)
starCom_401 = findCenterMass(s_positions_401,s_mass_401)
gasCom_401 = findCenterMass(g_positions_401,g_mass_401)

In [10]:
# comdata=open("centerofmass.txt","a")
# a=gasCom
# b=starCom
# c=nCom
# for val in zip(a,b,c):
#     comdata.write('{}'.format(val[0], val[1],val[2]))
# comdata.close()

In [11]:
# gin = np.loadtxt('centerofmass.txt', delimiter="\t")

In [67]:
gasCom_000.shape

(3,)

In [505]:
#Begin Jacob's method for doing shit
end = 5
snap = np.arange(0,end)
# blah = np.asarray([[gasCom_000,starCom_000,nCom_000],[gasCom_401,starCom_401,nCom_401]])
blah = []
#blah.tofile('centerofmass.txt',sep=',',format='%10.5f')
for x in (snap):
    print '%03d' %x
    filein = h5.File("simulation.hdf5/snap_%03d.hdf5.html" %x,'r')
    print filein
# for x in (snap):
#     blah.append(Gcom_000)
#     blah.append(Gcom_401)

# np.savetxt('centerofmass.txt',blah , fmt = '%10.5f', header='x y z')

000
<HDF5 file "snap_000.hdf5.html" (mode r)>
001


IOError: Unable to open file (Unable to open file: name = 'simulation.hdf5/snap_001.hdf5.html', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

In [492]:
blah

[array([  1.16131842e-03,   1.04191301e-03,   7.89113621e-05]),
 array([ -8.16478101, -21.06834398,   1.21260445])]

In [456]:
blah[0]

array([[  1.11618666e-02,   3.03726271e-03,  -4.18845052e-03],
       [  1.16131842e-03,   1.04191301e-03,   7.89113621e-05],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [457]:
blah[1]

array([[ -7.96355486, -20.84900284,   1.19367921],
       [ -8.15698548, -21.0649042 ,   1.21226275],
       [ -8.19847202, -21.08320999,   1.21408105]])

In [458]:
blah.shape

(2, 3, 3)

In [440]:
with open('centerofmass.txt','w') as f:
    np.savetxt(f,blah[:],delimiter = ",",fmt= '%.5f')


In [500]:
g = np.loadtxt('centerofmass.txt')

In [501]:
g[0]

array([  1.16000000e-03,   1.04000000e-03,   8.00000000e-05])

In [502]:
g[1]

array([ -8.16478, -21.06834,   1.2126 ])

In [503]:
g[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [472]:
g[3]

0.00116

In [473]:
g[:,0]

IndexError: too many indices for array

In [474]:
g[:,1]

IndexError: too many indices for array

In [475]:
g[:,2]

IndexError: too many indices for array

In [476]:
g[:1]

array([ 0.01116])

In [477]:
g[:,2]

IndexError: too many indices for array

In [478]:
g

array([  1.11600000e-02,   3.04000000e-03,  -4.19000000e-03,
         1.16000000e-03,   1.04000000e-03,   8.00000000e-05,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
        -7.96355000e+00,  -2.08490000e+01,   1.19368000e+00,
        -8.15699000e+00,  -2.10649000e+01,   1.21226000e+00,
        -8.19847000e+00,  -2.10832100e+01,   1.21408000e+00])

In [479]:
g.shape

(18,)

In [480]:
g[5]

8.0000000000000007e-05